#!/bin/bash

readarray -t words

declare -A word_counts

for word in "${words[@]}"; do
  ((word_counts["$word"]++))
done

for word in "${words[@]}"; do
  if [ "${word_counts["$word"]}" -eq 1 ]; then
    echo "$word"
  fi
done | sort
